ENZYME_LIB=/home/leila/Enzyme/enzyme/build18g/Enzyme/ClangEnzyme-18.so
CC = clang-18
CFLAGS += $(OPT) -Xclang -load -Xclang $(ENZYME_LIB) -Wall -Wextra -Wunused-variable -Wunused-function
LDFLAGS = -lm
